### ISSUE TITLE
Exploration: From issue template to branches

### ISSUE THREAD

**Issue by allejo** [cal-itp/calitp.org#435]
I've been thinking of a little experiment to build. I want to try improving the process of adding resources to this repository. Right now, we're using Issue Templates to get the appropriate information from users. The format for issues created from templates are pretty standard. So as long as the user doesn't modify the issue contents too much, we can parse the issue body with something like `GrantBirki/issue-template-parser`.

```yaml
steps:
  - name: Parse Issue
    id: parse-issue
    uses: GrantBirki/issue-template-parser@vX.X.X
    with:
      body: ${{ github.event.issue.body }}

  - name: Output Issue JSON
    id: output-issue
    run: echo ${{ steps.issue-parser.outputs.json }}
```

This method isn't 100% reliable as manual edits or weird syntax could break this parsing method. However, if everyone plays nice, then this should be able to get the job done. I think it's a risk I'm willing to take.

Moving on, once we've parsed the issue body, the next task is to create a new branch with a new file inside of `src/_resources`. Next up, using the JSON from the parsed issue contents, we can now write a file with the filled in information.

```bash
title="${{ fromJSON(steps.parse-issue.outputs.json).title }}"
file_name=$(echo $title | tr '\s' '-')

cat <<EOF > src/_resources/case-study-$file_name.md
---
date: ...
title: $title
---
EOF
```

Now, this code could be written in Bash and let it be embedded in the workflow. Or we could also write this as a Python script in the repo and simply execute it from the workflow. 

Lastly, you'd be able to use something like [`EndBug/add-and-commit`](https://github.com/EndBug/add-and-commit) to add and commit this file to the new branch.

---

What are your thoughts on investing time into building something like this?
